version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - run: python3 -m pip install --user --upgrade twine
      - run: python3 -m pip install --user --upgrade setuptools wheel
  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = MZorumski" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            python3 setup.py sdist bdist_wheel
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*
