jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - run: |
          echo $PYPI_PASS
workflows:
  version: 2
  my-workflow:
    jobs:
      - run-tests:
          context: mld-central
